// Stock Fundamentals Cheat Sheet - Core Data & Logic Engine

// --- METRIC DATABASE ---
const METRICS_DATA = [
  // 1️⃣ GROWTH
  {
    id: "revenue-growth",
    category: "growth",
    name: "Revenue Growth",
    acronym: "Sales Growth",
    memoryTrick: "Top-Line Expansion",
    direction: "higher", // "higher", "lower", "context"
    whatIsIt: "The percentage increase in total sales/revenue generated by the company over a specific period.",
    ideal: "🟢 10%–15%+ annually",
    whyItMatters: "Without revenue growth, a company cannot grow profits sustainably. It proves customer demand for products/services.",
    watchOut: "⚠ High revenue growth with declining profit margins means the company is buying growth at a loss.",
    beginnerMistake: "Assuming 50% revenue growth in a single year will continue forever.",
    bestComparedWith: ["Profit Growth", "Sales CAGR", "Operating Margin"],
    sectorChanges: ["FMCG (5-12% is normal)", "Utilities (Slow growth)", "IT & SaaS (15-30% expected)"],
    interpretation: [
      { value: ">20%", meaning: "Excellent", status: "excellent" },
      { value: "12%–20%", meaning: "Good", status: "good" },
      { value: "5%–12%", meaning: "Average", status: "average" },
      { value: "<5%", meaning: "Weak", status: "redflag" }
    ]
  },
  {
    id: "sales-cagr",
    category: "growth",
    name: "Sales CAGR",
    acronym: "3Y / 5Y CAGR",
    memoryTrick: "Smoothed Sales Growth",
    direction: "higher",
    whatIsIt: "Compound Annual Growth Rate of sales over 3, 5, or 10 years, smoothing out one-off cyclical spikes.",
    ideal: "🟢 >12% over 3–5 years",
    whyItMatters: "Filtering out one-year anomalies to show true long-term business trajectory.",
    watchOut: "⚠ Cyclical industries (metals, sugar) have misleading CAGR depending on start/end cycle years.",
    beginnerMistake: "Checking only 1-year sales growth instead of multi-year CAGR.",
    bestComparedWith: ["Profit CAGR", "Revenue Growth", "3Y Growth"],
    sectorChanges: ["Cyclical Sectors (Metals, Chemicals)", "Capital Goods"],
    interpretation: [
      { value: ">15%", meaning: "Excellent", status: "excellent" },
      { value: "10%–15%", meaning: "Good", status: "good" },
      { value: "5%–10%", meaning: "Average", status: "average" },
      { value: "<5%", meaning: "Poor", status: "redflag" }
    ]
  },
  {
    id: "profit-growth",
    category: "growth",
    name: "Profit Growth",
    acronym: "PAT Growth",
    memoryTrick: "Bottom-Line Expansion",
    direction: "higher",
    whatIsIt: "The rate at which Net Profit (Profit After Tax) grows year-over-year.",
    ideal: "🟢 >15% annually (faster than revenue)",
    whyItMatters: "If profit grows faster than revenue, the company enjoys operating leverage and margin expansion.",
    watchOut: "⚠ Profit growth driven purely by 'Other Income' or tax cuts rather than core operations.",
    beginnerMistake: "Ignoring Operating Profit and focusing only on Net Profit inflated by asset sales.",
    bestComparedWith: ["Revenue Growth", "EPS Growth", "Operating Margin"],
    sectorChanges: ["Airlines (Volatile)", "Capital Goods (Lumpy quarterly profits)"],
    interpretation: [
      { value: ">20%", meaning: "Excellent", status: "excellent" },
      { value: "15%–20%", meaning: "Good", status: "good" },
      { value: "8%–15%", meaning: "Average", status: "average" },
      { value: "<8%", meaning: "Weak", status: "redflag" }
    ]
  },
  {
    id: "eps-growth",
    category: "growth",
    name: "EPS Growth",
    acronym: "Earnings Per Share Growth",
    memoryTrick: "Per-Share Wealth Creation",
    direction: "higher",
    whatIsIt: "Growth in net income allocated to each outstanding share of common stock.",
    ideal: "🟢 >15% annually",
    whyItMatters: "Ensures share dilution (issuing new shares) isn't eroding shareholder value despite overall profit growth.",
    watchOut: "⚠ Share buybacks can boost EPS artificially even when net profit is flat.",
    beginnerMistake: "Looking only at total net profit without verifying if outstanding shares increased.",
    bestComparedWith: ["Profit Growth", "P/E Ratio", "PEG Ratio"],
    sectorChanges: ["Growth Tech", "Financials"],
    interpretation: [
      { value: ">20%", meaning: "Excellent", status: "excellent" },
      { value: "15%–20%", meaning: "Good", status: "good" },
      { value: "10%–15%", meaning: "Average", status: "average" },
      { value: "<10%", meaning: "Weak", status: "redflag" }
    ]
  },
  {
    id: "quarterly-growth",
    category: "growth",
    name: "Quarterly Growth",
    acronym: "QoQ / YoY Quarterly",
    memoryTrick: "Short-term Momentum",
    direction: "higher",
    whatIsIt: "Revenue and profit growth compared to the previous quarter (QoQ) or same quarter last year (YoY).",
    ideal: "🟢 Consistent YoY growth across quarters",
    whyItMatters: "Captures early turns in business cycles, turnaround stories, or accelerating execution.",
    watchOut: "⚠ Seasonal businesses (e.g. ice cream, festive retail) will have weak QoQ in off-seasons; always use YoY quarterly.",
    beginnerMistake: "Panicking over a weak Q2 when the business is inherently seasonal.",
    bestComparedWith: ["Sales CAGR", "Operating Margin"],
    sectorChanges: ["Retail", "Agrochemicals", "Capital Goods"],
    interpretation: [
      { value: ">15% YoY", meaning: "Excellent", status: "excellent" },
      { value: "10%–15%", meaning: "Good", status: "good" },
      { value: "0%–10%", meaning: "Average", status: "average" },
      { value: "<0%", meaning: "Negative / Declining", status: "redflag" }
    ]
  },

  // 2️⃣ PROFITABILITY
  {
    id: "roe",
    category: "profitability",
    name: "ROE (Return on Equity)",
    acronym: "ROE",
    memoryTrick: "Shareholder Efficiency",
    direction: "higher",
    whatIsIt: "How efficiently management generates profits from shareholders' invested capital.",
    ideal: "🟢 15%–20% or higher",
    whyItMatters: "High ROE shows management creates strong profits without needing excessive capital infusions.",
    watchOut: "⚠ High debt artificially inflates ROE! Always check Debt/Equity and ROCE alongside ROE.",
    beginnerMistake: "Buying a stock solely because ROE is 30%, without realizing 80% of assets are funded by debt.",
    bestComparedWith: ["ROCE", "Debt/Equity", "Net Margin"],
    sectorChanges: ["Banks", "Insurance", "Financial Services"],
    interpretation: [
      { value: ">20%", meaning: "Excellent", status: "excellent" },
      { value: "15%–20%", meaning: "Good", status: "good" },
      { value: "10%–15%", meaning: "Average", status: "average" },
      { value: "<10%", meaning: "Weak", status: "redflag" }
    ]
  },
  {
    id: "roce",
    category: "profitability",
    name: "ROCE (Return on Capital Employed)",
    acronym: "ROCE",
    memoryTrick: "Total Capital Efficiency",
    direction: "higher",
    whatIsIt: "Measures returns earned on ALL capital employed (Equity + Debt). The ultimate test of business quality.",
    ideal: "🟢 >15%–20%",
    whyItMatters: "Unlike ROE, ROCE cannot be cheated by taking on heavy debt. It shows true operating performance.",
    watchOut: "⚠ High cash balances earning low interest can suppress ROCE in cash-rich tech companies.",
    beginnerMistake: "Comparing ROCE of a software company (asset light) directly with a steel plant (asset heavy).",
    bestComparedWith: ["ROE", "ROIC", "Operating Margin"],
    sectorChanges: ["Capital Goods", "Manufacturing", "IT & SaaS"],
    interpretation: [
      { value: ">20%", meaning: "Excellent", status: "excellent" },
      { value: "15%–20%", meaning: "Good", status: "good" },
      { value: "10%–15%", meaning: "Average", status: "average" },
      { value: "<10%", meaning: "Poor", status: "redflag" }
    ]
  },
  {
    id: "operating-margin",
    category: "profitability",
    name: "Operating Margin",
    acronym: "OPM %",
    memoryTrick: "Core Business Margin",
    direction: "higher",
    whatIsIt: "Percentage of revenue left after paying variable costs of production (Operating Profit / Sales).",
    ideal: "🟢 >15%–20% (or industry leader)",
    whyItMatters: "Shows pricing power and cost efficiency in core business operations.",
    watchOut: "⚠ Fluctuations in raw material prices can squeeze OPM if company cannot pass costs to customers.",
    beginnerMistake: "Expecting high OPM in retail/supermarkets (where 4-8% is normal due to volume model).",
    bestComparedWith: ["EBITDA Margin", "Gross Margin", "Net Margin"],
    sectorChanges: ["FMCG (18-24%)", "Retail (4-8%)", "IT Services (20-25%)"],
    interpretation: [
      { value: ">20%", meaning: "Excellent", status: "excellent" },
      { value: "15%–20%", meaning: "Good", status: "good" },
      { value: "8%–15%", meaning: "Average", status: "average" },
      { value: "<8%", meaning: "Thin / Risk", status: "redflag" }
    ]
  },
  {
    id: "ebitda-margin",
    category: "profitability",
    name: "EBITDA Margin",
    acronym: "EBITDA %",
    memoryTrick: "Cash Earnings Margin",
    direction: "higher",
    whatIsIt: "Earnings before interest, tax, depreciation, and amortization divided by revenue.",
    ideal: "🟢 >18%–25%",
    whyItMatters: "Provides a clean look at cash profitability before accounting choices (depreciation methods).",
    watchOut: "⚠ Ignores heavy capital expenditure (CapEx) required to maintain equipment.",
    beginnerMistake: "Relying on EBITDA for capital-intensive companies where real depreciation costs are massive.",
    bestComparedWith: ["Operating Margin", "Free Cash Flow Margin"],
    sectorChanges: ["Telecom", "Infrastructure", "Real Estate"],
    interpretation: [
      { value: ">25%", meaning: "Excellent", status: "excellent" },
      { value: "18%–25%", meaning: "Good", status: "good" },
      { value: "10%–18%", meaning: "Average", status: "average" },
      { value: "<10%", meaning: "Weak", status: "redflag" }
    ]
  },
  {
    id: "net-margin",
    category: "profitability",
    name: "Net Profit Margin",
    acronym: "NPM %",
    memoryTrick: "Final Bottom-Line Keep",
    direction: "higher",
    whatIsIt: "Percentage of revenue remaining as net profit after ALL expenses, interest, and taxes.",
    ideal: "🟢 >10%–15%",
    whyItMatters: "Shows how much actual cash-convertible profit the business retains from every $100 of sales.",
    watchOut: "⚠ One-time extraordinary expenses or tax write-offs can distort single-year net margin.",
    beginnerMistake: "Ignoring interest expense impact when comparing high-debt vs low-debt peers.",
    bestComparedWith: ["Operating Margin", "ROE", "Free Cash Flow"],
    sectorChanges: ["Commodities", "Retail", "Software"],
    interpretation: [
      { value: ">15%", meaning: "Excellent", status: "excellent" },
      { value: "10%–15%", meaning: "Good", status: "good" },
      { value: "5%–10%", meaning: "Average", status: "average" },
      { value: "<5%", meaning: "Vulnerable", status: "redflag" }
    ]
  },

  // 3️⃣ FINANCIAL HEALTH
  {
    id: "debt-to-equity",
    category: "health",
    name: "Debt to Equity",
    acronym: "D/E Ratio",
    memoryTrick: "Solvency & Leverage Risk",
    direction: "lower",
    whatIsIt: "Total debt divided by total shareholders' equity. Measures financial leverage.",
    ideal: "🟢 <0.3 (Zero debt is ideal)",
    whyItMatters: "High debt creates interest burden and bankruptcy risk during economic downturns.",
    watchOut: "⚠ Banks and NBFCs naturally operate at D/E of 4.0–8.0! Do NOT filter out banks based on D/E.",
    beginnerMistake: "Applying D/E < 0.5 rule to banking and financial stocks.",
    bestComparedWith: ["Interest Coverage", "Current Ratio", "ROCE"],
    sectorChanges: ["Banks & NBFCs (Ignore D/E, check NPA & Capital Adequacy)", "Utilities (High debt normal)"],
    interpretation: [
      { value: "<0.3", meaning: "Excellent (Debt Free)", status: "excellent" },
      { value: "0.3–0.5", meaning: "Good / Manageable", status: "good" },
      { value: "0.5–1.0", meaning: "Moderate / Investigate", status: "average" },
      { value: ">1.0", meaning: "High Risk / Red Flag", status: "redflag" }
    ]
  },
  {
    id: "current-ratio",
    category: "health",
    name: "Current Ratio",
    acronym: "Liquidity Ratio",
    memoryTrick: "Short-term Survival Buffer",
    direction: "context",
    whatIsIt: "Current Assets divided by Current Liabilities. Measures ability to cover short-term debts due within 1 year.",
    ideal: "🟢 1.5–2.0",
    whyItMatters: "Ensures company won't face sudden cash crunch to pay suppliers, short loans, or operational bills.",
    watchOut: "⚠ A ratio > 3.0 may mean idle, inefficient cash or unsold bloated inventory.",
    beginnerMistake: "Thinking higher is always better; a ratio of 5.0 indicates bad capital allocation.",
    bestComparedWith: ["Quick Ratio", "Cash Reserves", "Operating Cash Flow"],
    sectorChanges: ["FMCG (Negative working capital can be good)", "Banks (Ignore)"],
    interpretation: [
      { value: "1.5–2.0", meaning: "Optimal", status: "excellent" },
      { value: "1.2–1.5", meaning: "Acceptable", status: "good" },
      { value: "1.0–1.2", meaning: "Tight Liquidity", status: "average" },
      { value: "<1.0", meaning: "High Insolvent Risk", status: "redflag" }
    ]
  },
  {
    id: "interest-coverage",
    category: "health",
    name: "Interest Coverage Ratio",
    acronym: "ICR",
    memoryTrick: "Debt Service Cushion",
    direction: "higher",
    whatIsIt: "EBIT (Operating Profit) divided by Interest Expense. Shows how easily company pays debt interest.",
    ideal: "🟢 >5.0x to 8.0x+",
    whyItMatters: "If operating profit falls by 30%, can the company still pay interest without defaulting?",
    watchOut: "⚠ ICR < 1.5x means profits barely cover interest payments. Default risk is imminent.",
    beginnerMistake: "Looking only at total debt amount without checking if profits easily cover annual interest.",
    bestComparedWith: ["Debt/Equity", "Operating Cash Flow", "EBITDA"],
    sectorChanges: ["Real Estate", "Infrastructure", "Power"],
    interpretation: [
      { value: ">8.0x", meaning: "Ultra Safe", status: "excellent" },
      { value: "5.0x–8.0x", meaning: "Healthy", status: "good" },
      { value: "2.0x–5.0x", meaning: "Caution", status: "average" },
      { value: "<2.0x", meaning: "Severe Default Risk", status: "redflag" }
    ]
  },

  // 4️⃣ VALUATION
  {
    id: "pe-ratio",
    category: "valuation",
    name: "Price to Earnings",
    acronym: "P/E Ratio",
    memoryTrick: "Price Paid Per $1 Profit",
    direction: "lower",
    whatIsIt: "Current Stock Price divided by Annual Earnings Per Share (EPS).",
    ideal: "🟢 Compare with 5-Yr historical P/E & industry average",
    whyItMatters: "Indicates how many years of current profit you are paying upfront to own the stock.",
    watchOut: "⚠ Low P/E can be a value trap! Dying businesses often trade at cheap P/E.",
    beginnerMistake: "Buying stock A (P/E 10) over stock B (P/E 30) without realizing B is growing 40% faster.",
    bestComparedWith: ["PEG Ratio", "Industry P/E", "ROE"],
    sectorChanges: ["Cyclicals (High P/E at peak earnings, low P/E at bottom - inverse rule!)"],
    interpretation: [
      { value: "< Industry Avg", meaning: "Potentially Undervalued", status: "excellent" },
      { value: "= Industry Avg", meaning: "Fair Value", status: "good" },
      { value: "1.5x Industry", meaning: "Growth Premium", status: "average" },
      { value: ">3x Industry", meaning: "Expensive / Overvalued", status: "redflag" }
    ]
  },
  {
    id: "peg-ratio",
    category: "valuation",
    name: "PEG Ratio",
    acronym: "PE to Growth",
    memoryTrick: "Growth-Adjusted Value",
    direction: "lower",
    whatIsIt: "P/E Ratio divided by Earnings Growth Rate (%). Adjusts P/E for growth velocity.",
    ideal: "🟢 < 1.0 (Bargain considering growth)",
    whyItMatters: "Peter Lynch's favorite metric. Equalizes fast-growing companies with slow-growing value stocks.",
    watchOut: "⚠ Using unsustainable 1-year profit spikes to calculate PEG leads to false bargains.",
    beginnerMistake: "Using PEG with negative earnings growth rate (mathematically meaningless).",
    bestComparedWith: ["P/E Ratio", "EPS Growth", "Revenue Growth"],
    sectorChanges: ["High-Growth Tech & SaaS"],
    interpretation: [
      { value: "< 0.8", meaning: "Strong Bargain", status: "excellent" },
      { value: "0.8–1.0", meaning: "Fair Value for Growth", status: "good" },
      { value: "1.0–1.5", meaning: "Slightly Premium", status: "average" },
      { value: "> 1.5", meaning: "Overvalued for Growth Rate", status: "redflag" }
    ]
  },
  {
    id: "price-to-book",
    category: "valuation",
    name: "Price to Book",
    acronym: "P/B Ratio",
    memoryTrick: "Price vs Liquidation Net Assets",
    direction: "lower",
    whatIsIt: "Stock Price divided by Book Value Per Share (Net Asset Value).",
    ideal: "🟢 < 1.0 to 3.0 (Sector dependent)",
    whyItMatters: "Crucial for asset-heavy businesses (Banks, Real Estate, Steel) to gauge asset backing.",
    watchOut: "⚠ Meaningless for IT/SaaS & Asset-light consumer brands with high intangible value.",
    beginnerMistake: "Ignoring P/B when valuing Banks & Financial Institutions.",
    bestComparedWith: ["ROE", "Book Value", "ROCE"],
    sectorChanges: ["Banks (Primary metric)", "IT & SaaS (Ignore P/B completely)"],
    interpretation: [
      { value: "< 1.5", meaning: "Attractive Asset Value", status: "excellent" },
      { value: "1.5–3.0", meaning: "Fair Asset Value", status: "good" },
      { value: "3.0–5.0", meaning: "Premium Asset Value", status: "average" },
      { value: "> 5.0", meaning: "High Premium / Check ROE", status: "redflag" }
    ]
  },

  // 5️⃣ OWNERSHIP
  {
    id: "promoter-holding",
    category: "ownership",
    name: "Promoter Holding",
    acronym: "Insider / Founder Stake",
    memoryTrick: "Skin in the Game",
    direction: "higher",
    whatIsIt: "Percentage of total company equity owned by original founders & promoters.",
    ideal: "🟢 >50% (or stable high stake)",
    whyItMatters: "High promoter holding ensures alignment of interest between management and shareholders.",
    watchOut: "⚠ Promoters systematically selling stake quarter after quarter is a huge warning sign.",
    beginnerMistake: "Assuming professionally managed companies (like L&T or ICICI) are bad because promoter stake is 0%.",
    bestComparedWith: ["Promoter Pledge", "FII / DII Holding", "Insider Buying"],
    sectorChanges: ["Professionally Managed Banks/Conglomerates (0% promoter is normal)"],
    interpretation: [
      { value: ">60%", meaning: "High Founder Skin in Game", status: "excellent" },
      { value: "45%–60%", meaning: "Healthy Alignment", status: "good" },
      { value: "30%–45%", meaning: "Moderate", status: "average" },
      { value: "<30%", meaning: "Low Stake / Watch Out", status: "redflag" }
    ]
  },
  {
    id: "promoter-pledge",
    category: "ownership",
    name: "Promoter Pledge",
    acronym: "Pledged Shares %",
    memoryTrick: "Mortgaged Founder Shares",
    direction: "lower",
    whatIsIt: "Percentage of promoter shares mortgaged as collateral to secure personal or corporate loans.",
    ideal: "🟢 0.0% (Zero pledge)",
    whyItMatters: "If stock price drops sharply, lenders margin call pledged shares, causing panic crash & takeover.",
    watchOut: "⚠ Any pledge above 15-20% is an absolute red flag in volatile market conditions.",
    beginnerMistake: "Confusing total promoter holding with pledged promoter holding.",
    bestComparedWith: ["Promoter Holding", "Debt/Equity", "Cash Flow"],
    sectorChanges: ["All sectors (Pledge is dangerous everywhere)"],
    interpretation: [
      { value: "0%", meaning: "Zero Risk (Clean)", status: "excellent" },
      { value: "< 5%", meaning: "Negligible", status: "good" },
      { value: "5%–15%", meaning: "Investigate Loan Terms", status: "average" },
      { value: "> 15%", meaning: "MAJOR RED FLAG 🔴", status: "redflag" }
    ]
  },

  // 6️⃣ CASH FLOW
  {
    id: "operating-cash-flow",
    category: "cashflow",
    name: "Operating Cash Flow",
    acronym: "OCF",
    memoryTrick: "Real Cash From Core Sales",
    direction: "higher",
    whatIsIt: "Actual cash generated from core business operations after working capital adjustments.",
    ideal: "🟢 OCF > Net Profit consistently",
    whyItMatters: "Accounting profit can be faked; cash in bank account cannot. OCF proves real revenue quality.",
    watchOut: "⚠ Growing profits with negative operating cash flow indicates revenue is stuck in unpaid receivables.",
    beginnerMistake: "Trusting net profit growth without checking if OCF is positive.",
    bestComparedWith: ["Free Cash Flow", "Net Profit", "Cash Conversion Cycle"],
    sectorChanges: ["All sectors"],
    interpretation: [
      { value: "OCF > Net Profit", meaning: "High Quality Cash Earnings", status: "excellent" },
      { value: "OCF ≈ Net Profit", meaning: "Healthy Cash Conversion", status: "good" },
      { value: "OCF < 50% Profit", meaning: "Working Capital Trap", status: "average" },
      { value: "Negative OCF", meaning: "Cash Bleed RED FLAG 🔴", status: "redflag" }
    ]
  },
  {
    id: "free-cash-flow",
    category: "cashflow",
    name: "Free Cash Flow",
    acronym: "FCF",
    memoryTrick: "Surplus Discretionary Cash",
    direction: "higher",
    whatIsIt: "Cash left over after paying for essential business operations and capital expenditures (CapEx). OCF - CapEx.",
    ideal: "🟢 Positive & growing year-over-year",
    whyItMatters: "FCF pays for dividends, debt reduction, share buybacks, and strategic acquisitions.",
    watchOut: "⚠ Heavy growth phase companies may have temporary low FCF due to massive strategic expansion CapEx.",
    beginnerMistake: "Demanding high FCF from a young company building its first factories.",
    bestComparedWith: ["Operating Cash Flow", "CapEx", "Dividend Yield"],
    sectorChanges: ["Tech/SaaS (High FCF)", "Infra & Telecom (Low/Delayed FCF)"],
    interpretation: [
      { value: "High Positive FCF", meaning: "Cash Machine", status: "excellent" },
      { value: "Modest Positive FCF", meaning: "Stable Cash Generator", status: "good" },
      { value: "Flat FCF", meaning: "Reinvesting All Cash", status: "average" },
      { value: "Consistently Negative FCF", meaning: "Capital Furnace", status: "redflag" }
    ]
  },

  // 7️⃣ QUALITY & GOVERNANCE
  {
    id: "moat-brand",
    category: "quality",
    name: "Economic Moat & Brand",
    acronym: "Competitive Advantage",
    memoryTrick: "Business Fortress Wall",
    direction: "higher",
    whatIsIt: "Structural competitive advantage protecting company profits from competitors (Network effects, Brand, Switching costs, Cost advantage).",
    ideal: "🟢 Wide Moat with high pricing power",
    whyItMatters: "High margins attract competitors. Without a moat, high ROE collapses over time.",
    watchOut: "⚠ Confusing temporary market supply shortage with a permanent economic moat.",
    beginnerMistake: "Investing in pure commodity suppliers assuming current high margins will last.",
    bestComparedWith: ["Operating Margin", "ROCE", "Gross Margin"],
    sectorChanges: ["FMCG, Consumer Tech, Pharma"],
    interpretation: [
      { value: "Wide Moat", meaning: "Monopoly / Pricing Power Leader", status: "excellent" },
      { value: "Narrow Moat", meaning: "Strong Brand Recognition", status: "good" },
      { value: "No Moat", meaning: "Pure Commodity / Price Taker", status: "average" },
      { value: "Eroding Moat", meaning: "Disrupted by Tech/New Competitor", status: "redflag" }
    ]
  },
  {
    id: "accounting-red-flags",
    category: "quality",
    name: "Corporate Governance & Accounting",
    acronym: "Governance Checks",
    memoryTrick: "Management Integrity",
    direction: "higher",
    whatIsIt: "Audit quality, related party transactions, auditor changes, promoter compensation, and ledger transparency.",
    ideal: "🟢 Clean Big 4 / top auditor, zero related party loans",
    whyItMatters: "Bad governance ruins great financial numbers. Fraud zeroizes capital instantly.",
    watchOut: "⚠ Frequent auditor resignations mid-term citing 'unavailability of financial data'.",
    beginnerMistake: "Ignoring related party transactions where promoters siphon cash to private subsidiaries.",
    bestComparedWith: ["Promoter Pledge", "Receivables Growth", "Cash Reserves"],
    sectorChanges: ["All sectors"],
    interpretation: [
      { value: "Clean Audit", meaning: "Top Tier Governance", status: "excellent" },
      { value: "Minor Related Party", meaning: "Standard / Disclosed", status: "good" },
      { value: "Unexplained Loans", meaning: "Caution / Audit Queries", status: "average" },
      { value: "Auditor Resigned", meaning: "IMMEDIATE EXIT RED FLAG 🔴", status: "redflag" }
    ]
  }
];

// --- 60 SECOND CHECKLIST ITEMS ---
const CHECKLIST_ITEMS = [
  { id: "chk1", label: "Revenue growing? (>10% YoY / multi-year CAGR)", metricId: "revenue-growth" },
  { id: "chk2", label: "Profit growing? (PAT & EPS growing faster than sales)", metricId: "profit-growth" },
  { id: "chk3", label: "ROE > 15%? (High return on equity capital)", metricId: "roe" },
  { id: "chk4", label: "ROCE > 15%? (High return on total capital employed)", metricId: "roce" },
  { id: "chk5", label: "Debt manageable? (Debt/Equity < 0.5 or Interest Coverage > 5x)", metricId: "debt-to-equity" },
  { id: "chk6", label: "Positive Cash Flow? (Operating Cash Flow > Net Profit)", metricId: "operating-cash-flow" },
  { id: "chk7", label: "Promoter pledge = 0%? (No mortgaged shares)", metricId: "promoter-pledge" },
  { id: "chk8", label: "Valuation reasonable? (P/E & PEG aligned with growth)", metricId: "peg-ratio" }
];

// --- BIGGEST RED FLAGS CATALOG ---
const RED_FLAGS_CATALOG = [
  {
    title: "🔴 Promoter Pledging Increasing",
    desc: "Promoters pledging >15% of their shares to raise cash. Stock price drop forces margin calls, causing catastrophic panic selling.",
    action: "Rule: Avoid or exit immediately if promoter pledge rises quarter over quarter."
  },
  {
    title: "🔴 Negative Operating Cash Flow with Rising Profits",
    desc: "Net profit is growing on paper, but Operating Cash Flow (OCF) is zero or negative. Profits are fake or trapped in uncollected bills.",
    action: "Rule: Compare OCF vs Net Profit over 3 years. OCF must track Profit."
  },
  {
    title: "🔴 Sales Growing but Profit Falling",
    desc: "Revenue increases by 25% but net profit declines by 10%. Shows severe margin compression, inability to pass on costs, or predatory pricing.",
    action: "Rule: Check Operating Margin trend over 4 quarters."
  },
  {
    title: "🔴 High Debt with Falling Profits & Interest Coverage < 2x",
    desc: "Company takes heavy debt for expansion, but profits shrink. Interest cost eats up all operational earnings.",
    action: "Rule: Reject companies with Debt/Equity > 1.0 and Interest Coverage < 2.0x."
  },
  {
    title: "🔴 Frequent Equity Dilution",
    desc: "Number of outstanding shares keeps increasing every year to fund losses, diluting existing shareholders' value.",
    action: "Rule: Check 5-Year Share Capital trend. It should be flat or decreasing."
  },
  {
    title: "🔴 Sudden Auditor Resignation Mid-Year",
    desc: "Independent auditor resigns before signing financial results, citing 'lack of management disclosure' or accounting disagreements.",
    action: "Rule: Immediate dealbreaker. Sell or stay away."
  },
  {
    title: "🔴 Falling Promoter Holding Quarter over Quarter",
    desc: "Founders dumping stake quietly over 4 consecutive quarters while talking bullishly in news interviews.",
    action: "Rule: Track Shareholding Pattern quarterly changes on Screener.in."
  },
  {
    title: "🔴 Trade Receivables Growing Faster than Sales",
    desc: "Receivables jump 50% while revenue grows only 10%. Shows company is stuffing channels or offering dangerous credit terms.",
    action: "Rule: Check Days Sales Outstanding (DSO) and Cash Conversion Cycle."
  }
];

// --- SECTOR EXCEPTIONS MATRIX ---
const SECTOR_EXCEPTIONS = [
  {
    sector: "Banks & NBFCs",
    ignore: ["Debt/Equity", "Current Ratio", "EV/EBITDA"],
    why: "Taking deposits (debt) is their main business model. High D/E is normal.",
    focus: ["Net NPA < 1.0%", "CASA Ratio > 40%", "NIM > 3.5%", "Capital Adequacy (CAR > 15%)"]
  },
  {
    sector: "Insurance Companies",
    ignore: ["Debt/Equity", "P/E Ratio", "Operating Margin"],
    why: "Insurance accounting uses actuarial reserves instead of standard EBITDA.",
    focus: ["Solvency Ratio > 150%", "Combined Ratio < 100%", "Embedded Value (EV)", "Persistency Ratio"]
  },
  {
    sector: "IT & SaaS",
    ignore: ["Price to Book (P/B)", "Fixed Asset Turnover"],
    why: "Software companies own intellectual property & human capital, not massive physical factories.",
    focus: ["ROCE > 25%", "Operating Margin > 20%", "Free Cash Flow Conversion", "Attrition Rate"]
  },
  {
    sector: "FMCG / Consumer Staples",
    ignore: ["Hyper Sales Growth (>20%)"],
    why: "Mature market leaders grow steadily at 8–14% while giving high cash returns.",
    focus: ["ROCE > 30%", "Brand Moat & Pricing Power", "Working Capital Cycle", "Distribution Reach"]
  },
  {
    sector: "Utilities & Power",
    ignore: ["Low P/E (<10x)", "Fast Revenue Growth"],
    why: "Regulated capital-intensive sectors with capped returns on equity.",
    focus: ["Dividend Yield", "Regulated Equity Return", "Debt Service Coverage Ratio (DSCR)"]
  },
  {
    sector: "Airlines & Aviation",
    ignore: ["Single Year P/E", "High Quarterly Margin"],
    why: "Extremely cyclical, fuel-price dependent, capital intensive with low pricing power.",
    focus: ["Passenger Load Factor (PLF)", "RASK vs CASK", "Lease Debt & Liquidity Cushion"]
  },
  {
    sector: "Real Estate & Construction",
    ignore: ["Standard P/E Ratio"],
    why: "Revenue recognition depends on project completion timelines, creating lumpy quarterly profits.",
    focus: ["Pre-sales Growth", "Net Debt to EBITDA", "Collections vs Outflow", "Inventory Days"]
  },
  {
    sector: "Capital Goods & Engineering",
    ignore: ["Quarterly Profit Volatility"],
    why: "Long execution cycles of 2-4 years make quarterly numbers naturally volatile.",
    focus: ["Order Book to Sales Ratio (>2.5x)", "Working Capital % of Sales", "Multi-year Execution"]
  }
];

// --- QUICK REFERENCE SUMMARY TABLES ---
const QUICK_REFERENCE_TABLES = [
  {
    title: "Profitability & Efficiency Cheat Sheet",
    headers: ["Metric", "🟢 Excellent", "🟢 Good", "🟡 Average", "🔴 Poor / Flag"],
    rows: [
      { name: "ROE (Return on Equity)", exc: ">20%", good: "15%–20%", avg: "10%–15%", poor: "<10%" },
      { name: "ROCE (Return on Capital)", exc: ">20%", good: "15%–20%", avg: "10%–15%", poor: "<10%" },
      { name: "Operating Margin (OPM)", exc: ">20%", good: "15%–20%", avg: "8%–15%", poor: "<8%" },
      { name: "Net Profit Margin", exc: ">15%", good: "10%–15%", avg: "5%–10%", poor: "<5%" }
    ]
  },
  {
    title: "Financial Health & Solvency Cheat Sheet",
    headers: ["Metric", "🟢 Excellent", "🟢 Good", "🟡 Average", "🔴 Poor / Flag"],
    rows: [
      { name: "Debt to Equity", exc: "<0.3 (Debt Free)", good: "0.3–0.5", avg: "0.5–1.0", poor: ">1.0" },
      { name: "Current Ratio", exc: "1.5–2.0", good: "1.2–1.5", avg: "1.0–1.2", poor: "<1.0" },
      { name: "Interest Coverage", exc: ">8.0x", good: "5.0x–8.0x", avg: "2.0x–5.0x", poor: "<2.0x" },
      { name: "Promoter Pledge", exc: "0.0%", good: "<5.0%", avg: "5%–15%", poor: ">15.0%" }
    ]
  }
];

// --- APPLICATION STATE ---
let currentCategory = 'all';
let currentSearchQuery = '';
let bookmarkedMetricIds = JSON.parse(localStorage.getItem('briefstocks_bookmarks') || '[]');
let checklistState = JSON.parse(localStorage.getItem('briefstocks_checklist') || '{}');

// --- INITIALIZATION ---
document.addEventListener('DOMContentLoaded', () => {
  renderChecklist();
  renderNavTabs();
  renderMetrics();
  renderRedFlags();
  renderSectorExceptions();
  renderQuickReferenceTables();
  setupEventListeners();
  updateChecklistScore();
});

// --- EVENT LISTENERS ---
function setupEventListeners() {
  const searchInput = document.getElementById('search-input');
  const catalogSearchInput = document.getElementById('catalog-search-input');

  if (searchInput) {
    searchInput.addEventListener('input', (e) => {
      currentSearchQuery = e.target.value.toLowerCase().trim();
      if (catalogSearchInput) catalogSearchInput.value = e.target.value;
      renderMetrics();
    });
  }

  if (catalogSearchInput) {
    catalogSearchInput.addEventListener('input', (e) => {
      currentSearchQuery = e.target.value.toLowerCase().trim();
      if (searchInput) searchInput.value = e.target.value;
      renderMetrics();
    });
  }

  // Keyboard shortcut Ctrl+K / '/' for search
  document.addEventListener('keydown', (e) => {
    if ((e.ctrlKey || e.metaKey) && e.key === 'k') {
      e.preventDefault();
      if (catalogSearchInput) catalogSearchInput.focus();
      else if (searchInput) searchInput.focus();
    } else if (e.key === '/' && document.activeElement !== searchInput && document.activeElement !== catalogSearchInput) {
      e.preventDefault();
      if (catalogSearchInput) catalogSearchInput.focus();
      else if (searchInput) searchInput.focus();
    }
  });

  // Screener Evaluator Form
  const evaluatorForm = document.getElementById('screener-eval-form');
  if (evaluatorForm) {
    evaluatorForm.addEventListener('submit', (e) => {
      e.preventDefault();
      runLiveScreenerEvaluation();
    });
  }
}

// --- RENDER NAV TABS ---
function renderNavTabs() {
  const navContainer = document.getElementById('category-nav-inner');
  if (!navContainer) return;

  const categories = [
    { id: 'all', label: 'All Metrics', icon: 'icon-quality', count: METRICS_DATA.length },
    { id: 'growth', label: '1️⃣ Growth', icon: 'icon-growth', count: METRICS_DATA.filter(m => m.category==='growth').length },
    { id: 'profitability', label: '2️⃣ Profitability', icon: 'icon-profit', count: METRICS_DATA.filter(m => m.category==='profitability').length },
    { id: 'health', label: '3️⃣ Financial Health', icon: 'icon-health', count: METRICS_DATA.filter(m => m.category==='health').length },
    { id: 'valuation', label: '4️⃣ Valuation', icon: 'icon-valuation', count: METRICS_DATA.filter(m => m.category==='valuation').length },
    { id: 'ownership', label: '5️⃣ Ownership', icon: 'icon-ownership', count: METRICS_DATA.filter(m => m.category==='ownership').length },
    { id: 'cashflow', label: '6️⃣ Cash Flow', icon: 'icon-cashflow', count: METRICS_DATA.filter(m => m.category==='cashflow').length },
    { id: 'quality', label: '7️⃣ Quality & Moat', icon: 'icon-quality', count: METRICS_DATA.filter(m => m.category==='quality').length },
    { id: 'saved', label: '⭐ Bookmarks', icon: 'icon-bookmark', count: bookmarkedMetricIds.length }
  ];

  navContainer.innerHTML = categories.map(cat => `
    <button class="nav-tab ${cat.id === currentCategory ? 'active' : ''}" onclick="setCategory('${cat.id}')">
      <span>${cat.label}</span>
      <span class="badge-count">${cat.count}</span>
    </button>
  `).join('');
}

function setCategory(catId) {
  currentCategory = catId;
  renderNavTabs();
  renderMetrics();
}

// --- RENDER METRICS CARDS ---
function renderMetrics() {
  const container = document.getElementById('metrics-container');
  const countBadge = document.getElementById('catalog-count-badge');
  const scrollContainer = document.getElementById('catalog-scroll-container');
  if (!container) return;

  let filtered = METRICS_DATA.filter(metric => {
    // Category filter
    if (currentCategory === 'saved') {
      if (!bookmarkedMetricIds.includes(metric.id)) return false;
    } else if (currentCategory !== 'all' && metric.category !== currentCategory) {
      return false;
    }

    // Search query filter
    if (currentSearchQuery) {
      const q = currentSearchQuery;
      const matchName = metric.name.toLowerCase().includes(q);
      const matchAcronym = metric.acronym.toLowerCase().includes(q);
      const matchMemory = metric.memoryTrick.toLowerCase().includes(q);
      const matchDesc = metric.whatIsIt.toLowerCase().includes(q);
      const matchWhy = metric.whyItMatters.toLowerCase().includes(q);

      return matchName || matchAcronym || matchMemory || matchDesc || matchWhy;
    }

    return true;
  });

  if (countBadge) {
    countBadge.innerText = `Showing ${filtered.length} of ${METRICS_DATA.length} Metrics`;
  }

  if (filtered.length === 0) {
    container.innerHTML = `
      <div style="grid-column: 1 / -1; text-align: center; padding: 40px; color: var(--text-muted);">
        <p style="font-size: 1.1rem; font-weight: 700; margin-bottom: 8px;">No metrics found matching "${currentSearchQuery}"</p>
        <p style="font-size: 0.88rem;">Try searching for keywords like "ROE", "P/E", "Debt", "Margin", "Cash Flow", or reset filters.</p>
      </div>
    `;
    return;
  }

  container.innerHTML = filtered.map(metric => createMetricCardHtml(metric)).join('');
  if (scrollContainer && currentSearchQuery) {
    scrollContainer.scrollTop = 0;
  }
}

function createMetricCardHtml(metric) {
  const isBookmarked = bookmarkedMetricIds.includes(metric.id);
  const dirClass = metric.direction === 'higher' ? 'direction-higher' : (metric.direction === 'lower' ? 'direction-lower' : 'direction-context');
  const dirLabel = metric.direction === 'higher' ? '⬆ Higher is Better' : (metric.direction === 'lower' ? '⬇ Lower is Better' : '⚖ Sector Dependent');

  return `
    <div class="metric-card animate-fade" id="metric-${metric.id}">
      <div class="metric-card-header">
        <div class="metric-name-box">
          <div class="metric-title">
            <span>${metric.name}</span>
            <span class="metric-acronym">(${metric.acronym})</span>
          </div>
          <div class="memory-trick-pill">
            💡 Quick Trick: ${metric.memoryTrick}
          </div>
        </div>

        <button class="btn btn-ghost" style="padding: 4px 8px;" title="Bookmark metric" onclick="toggleBookmark('${metric.id}')">
          <svg style="stroke: ${isBookmarked ? 'var(--brand-cyan)' : 'var(--text-secondary)'}; fill: ${isBookmarked ? 'var(--brand-cyan)' : 'none'}">
            <use href="assets/icons.svg#icon-bookmark"></use>
          </svg>
        </button>
      </div>

      <div class="info-block">
        <div class="info-label">What is it?</div>
        <div class="info-content">${metric.whatIsIt}</div>
      </div>

      <div class="info-block" style="background: rgba(16, 185, 129, 0.06); border-color: rgba(16, 185, 129, 0.2);">
        <div class="info-label" style="color: var(--excellent-color);">Ideal Target</div>
        <div class="ideal-range-value">${metric.ideal}</div>
      </div>

      <div class="info-block">
        <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 6px;">
          <div class="info-label">Interpretation Table</div>
          <span class="direction-badge ${dirClass}">${dirLabel}</span>
        </div>
        <table class="interpret-table">
          <thead>
            <tr>
              <th>Range / Value</th>
              <th>Meaning / Status</th>
            </tr>
          </thead>
          <tbody>
            ${metric.interpretation.map(row => `
              <tr>
                <td><span class="val-badge val-${row.status}">${row.value}</span></td>
                <td style="font-weight: 600; color: var(--${row.status === 'redflag' ? 'redflag-color' : (row.status === 'excellent' ? 'excellent-color' : (row.status === 'good' ? 'good-color' : 'average-color'))});">
                  ${row.meaning}
                </td>
              </tr>
            `).join('')}
          </tbody>
        </table>
      </div>

      <div class="info-block">
        <div class="info-label">Why Investors Care</div>
        <div class="info-content" style="font-size: 0.85rem;">${metric.whyItMatters}</div>
      </div>

      <div class="watchout-box">
        <div class="callout-title">⚠ Watch Out!</div>
        <div>${metric.watchOut}</div>
      </div>

      <div class="mistake-box">
        <div class="callout-title">🚫 Beginner Mistake</div>
        <div>${metric.beginnerMistake}</div>
      </div>

      <div>
        <div class="info-label">Best Compared With</div>
        <div class="tag-group">
          ${metric.bestComparedWith.map(item => `
            <span class="tag-btn" onclick="searchMetric('${item}')">${item}</span>
          `).join('')}
        </div>
      </div>

      <div>
        <div class="info-label">Industries Where This Changes</div>
        <div class="tag-group">
          ${metric.sectorChanges.map(sec => `
            <span class="sector-tag">🏢 ${sec}</span>
          `).join('')}
        </div>
      </div>
    </div>
  `;
}

// --- BOOKMARK TOGGLE ---
function toggleBookmark(id) {
  if (bookmarkedMetricIds.includes(id)) {
    bookmarkedMetricIds = bookmarkedMetricIds.filter(bId => bId !== id);
  } else {
    bookmarkedMetricIds.push(id);
  }
  localStorage.setItem('briefstocks_bookmarks', JSON.stringify(bookmarkedMetricIds));
  renderNavTabs();
  renderMetrics();
}

function searchMetric(term) {
  const searchInput = document.getElementById('search-input');
  const catalogSearchInput = document.getElementById('catalog-search-input');
  if (searchInput) searchInput.value = term;
  if (catalogSearchInput) catalogSearchInput.value = term;
  currentSearchQuery = term.toLowerCase();
  renderMetrics();
  
  const catalogSection = document.getElementById('metrics-section');
  if (catalogSection) {
    catalogSection.scrollIntoView({ behavior: 'smooth' });
  }
}

// --- RENDER 60 SECOND CHECKLIST ---
function renderChecklist() {
  const grid = document.getElementById('checklist-grid');
  if (!grid) return;

  grid.innerHTML = CHECKLIST_ITEMS.map(item => {
    const isChecked = !!checklistState[item.id];
    return `
      <div class="check-item ${isChecked ? 'checked' : ''}" onclick="toggleChecklistItem('${item.id}')">
        <div class="custom-checkbox">
          <svg><use href="assets/icons.svg#icon-check"></use></svg>
        </div>
        <div class="check-text">${item.label}</div>
      </div>
    `;
  }).join('');
}

function toggleChecklistItem(id) {
  checklistState[id] = !checklistState[id];
  localStorage.setItem('briefstocks_checklist', JSON.stringify(checklistState));
  renderChecklist();
  updateChecklistScore();
}

function resetChecklist() {
  checklistState = {};
  localStorage.setItem('briefstocks_checklist', JSON.stringify(checklistState));
  renderChecklist();
  updateChecklistScore();
}

function updateChecklistScore() {
  const count = Object.values(checklistState).filter(Boolean).length;
  const total = CHECKLIST_ITEMS.length;
  const pct = Math.round((count / total) * 100);

  const fill = document.getElementById('score-bar-fill');
  const scoreText = document.getElementById('checklist-score-text');
  const verdictPill = document.getElementById('verdict-pill');

  if (fill) fill.style.width = `${pct}%`;
  if (scoreText) scoreText.innerText = `${count} / ${total} Checks Passed (${pct}%)`;

  if (verdictPill) {
    if (count === 8) {
      verdictPill.innerText = "🟢 Excellent Candidate (Pass)";
      verdictPill.style.color = "var(--excellent-color)";
      verdictPill.style.background = "var(--excellent-bg)";
    } else if (count >= 6) {
      verdictPill.innerText = "🟢 Good Candidate (Investigate)";
      verdictPill.style.color = "var(--good-color)";
      verdictPill.style.background = "var(--good-bg)";
    } else if (count >= 4) {
      verdictPill.innerText = "🟡 Moderate (Deep Dive Needed)";
      verdictPill.style.color = "var(--average-color)";
      verdictPill.style.background = "var(--average-bg)";
    } else {
      verdictPill.innerText = "🔴 High Risk / Failed Checklist";
      verdictPill.style.color = "var(--redflag-color)";
      verdictPill.style.background = "var(--redflag-bg)";
    }
  }
}

// --- RENDER RED FLAGS CATALOG ---
function renderRedFlags() {
  const container = document.getElementById('redflags-grid');
  if (!container) return;

  container.innerHTML = RED_FLAGS_CATALOG.map(rf => `
    <div class="redflag-card">
      <div class="redflag-title">${rf.title}</div>
      <div class="redflag-desc">${rf.desc}</div>
      <div class="redflag-action">💡 ${rf.action}</div>
    </div>
  `).join('');
}

// --- RENDER SECTOR EXCEPTIONS ---
function renderSectorExceptions() {
  const tbody = document.getElementById('sector-table-body');
  if (!tbody) return;

  tbody.innerHTML = SECTOR_EXCEPTIONS.map(sec => `
    <tr>
      <td class="sector-name-cell">🏢 ${sec.sector}</td>
      <td>
        ${sec.ignore.map(ig => `<span class="ignore-pill">🚫 Ignore ${ig}</span>`).join('')}
      </td>
      <td style="font-size: 0.85rem; color: var(--text-secondary);">${sec.why}</td>
      <td>
        ${sec.focus.map(f => `<span class="focus-pill">🎯 ${f}</span>`).join('')}
      </td>
    </tr>
  `).join('');
}

// --- RENDER QUICK REFERENCE TABLES ---
function renderQuickReferenceTables() {
  const container = document.getElementById('quick-reference-container');
  if (!container) return;

  container.innerHTML = QUICK_REFERENCE_TABLES.map(tbl => `
    <div class="reference-table-container">
      <div style="padding: 14px 18px; font-weight: 800; font-size: 1rem; border-bottom: 1px solid var(--border-color); background: rgba(0,0,0,0.2);">
        📊 ${tbl.title}
      </div>
      <table class="ref-table">
        <thead>
          <tr>
            ${tbl.headers.map(h => `<th>${h}</th>`).join('')}
          </tr>
        </thead>
        <tbody>
          ${tbl.rows.map(r => `
            <tr>
              <td style="font-weight: 700; color: var(--brand-cyan);">${r.name}</td>
              <td class="val-cell" style="color: var(--excellent-color);">${r.exc}</td>
              <td class="val-cell" style="color: var(--good-color);">${r.good}</td>
              <td class="val-cell" style="color: var(--average-color);">${r.avg}</td>
              <td class="val-cell" style="color: var(--redflag-color);">${r.poor}</td>
            </tr>
          `).join('')}
        </tbody>
      </table>
    </div>
  `).join('');
}

// --- LIVE SCREENER EVALUATOR WIDGET ---
function runLiveScreenerEvaluation() {
  const roeVal = parseFloat(document.getElementById('input-roe')?.value) || 0;
  const roceVal = parseFloat(document.getElementById('input-roce')?.value) || 0;
  const deVal = parseFloat(document.getElementById('input-de')?.value) || 0;
  const peVal = parseFloat(document.getElementById('input-pe')?.value) || 0;
  const pegVal = parseFloat(document.getElementById('input-peg')?.value) || 0;
  const pledgeVal = parseFloat(document.getElementById('input-pledge')?.value) || 0;

  const outputBox = document.getElementById('evaluation-output');
  if (!outputBox) return;

  outputBox.classList.add('active');

  const findings = [];
  let score = 0;

  // ROE check
  if (roeVal >= 20) { findings.push("🟢 ROE is Excellent (>20%)"); score += 2; }
  else if (roeVal >= 15) { findings.push("🟢 ROE is Good (15-20%)"); score += 1.5; }
  else { findings.push("🔴 ROE is Weak (<15%)"); }

  // ROCE check
  if (roceVal >= 20) { findings.push("🟢 ROCE is Excellent (>20%)"); score += 2; }
  else if (roceVal >= 15) { findings.push("🟢 ROCE is Good (15-20%)"); score += 1.5; }
  else { findings.push("🔴 ROCE is Below Target (<15%)"); }

  // Debt/Equity check
  if (deVal <= 0.3) { findings.push("🟢 Debt/Equity is Debt-Free / Excellent (<0.3)"); score += 2; }
  else if (deVal <= 0.5) { findings.push("🟢 Debt/Equity is Manageable (0.3-0.5)"); score += 1; }
  else { findings.push("🔴 High Financial Leverage (Debt/Equity > 0.5)"); }

  // PEG check
  if (pegVal > 0 && pegVal <= 1.0) { findings.push("🟢 PEG Ratio shows Great Growth Value (<1.0)"); score += 2; }
  else if (pegVal > 1.0) { findings.push("🟡 PEG Ratio is Fair/Expensive (>1.0)"); score += 0.5; }

  // Pledge check
  if (pledgeVal === 0) { findings.push("🟢 Zero Promoter Pledge (Clean)"); score += 2; }
  else if (pledgeVal > 15) { findings.push("🔴 MAJOR RED FLAG: High Promoter Pledge (>15%)"); score -= 3; }

  let statusHtml = `
    <div style="font-weight: 800; font-size: 1.1rem; margin-bottom: 10px; color: ${score >= 7 ? 'var(--excellent-color)' : (score >= 4 ? 'var(--average-color)' : 'var(--redflag-color)')}">
      Evaluation Verdict: ${score >= 7 ? '🟢 Strong Fundamental Profile' : (score >= 4 ? '🟡 Moderate Profile - Deeper Audit Needed' : '🔴 High Risk Profile')}
    </div>
    <ul style="list-style: none; padding: 0; display: flex; flex-direction: column; gap: 6px;">
      ${findings.map(f => `<li style="font-size: 0.88rem; font-weight: 600;">${f}</li>`).join('')}
    </ul>
  `;

  outputBox.innerHTML = statusHtml;
}
